/**
 * NER-LOGIX operational SIMULATION data.
 *
 * Nothing in this file is government data. Every export here is generated by
 * NER-LOGIX for prototype purposes and must be labelled as such in the UI.
 * Later stages replace these exports with live system data without changing
 * the consuming components' props shape.
 */
import type {
  DataSource,
  Incident,
  RiskLevel,
  TransportMission,
  Vehicle,
} from "@/services/types";

export type { RiskLevel };

export const RISK_META: Record<RiskLevel, { label: string; token: string }> = {
  safe: { label: "Safe", token: "safe" },
  moderate: { label: "Moderate Risk", token: "moderate" },
  high: { label: "High Risk", token: "high" },
  blocked: { label: "Blocked", token: "blocked" },
};

/** Simulated fleet positions (WGS84). */
export const VEHICLES: Vehicle[] = [
  { id: "LG-114", kind: "logistics", label: "LG-114", lat: 27.42, lng: 94.85, source: "NER-LOGIX Simulation" },
  { id: "LG-208", kind: "logistics", label: "LG-208", lat: 26.75, lng: 94.21, source: "NER-LOGIX Simulation" },
  { id: "LG-331", kind: "logistics", label: "LG-331", lat: 26.18, lng: 91.75, source: "NER-LOGIX Simulation" },
  { id: "MD-051", kind: "medical", label: "MD-051", lat: 25.57, lng: 91.88, source: "NER-LOGIX Simulation" },
  { id: "MD-077", kind: "medical", label: "MD-077", lat: 24.82, lng: 92.79, source: "NER-LOGIX Simulation" },
];

/** Simulated incident reports awaiting the Step-3 reporting pipeline. */
export const INCIDENTS: Incident[] = [
  { id: "INC-2291", type: "Landslide", severity: "blocked", districtId: "east-jaintia-hills", reportedAt: "51 min ago", source: "NER-LOGIX Reports" },
  { id: "INC-2288", type: "Flooding", severity: "high", districtId: "cachar", reportedAt: "1h 24m ago", source: "NER-LOGIX Reports" },
  { id: "INC-2284", type: "Road erosion", severity: "moderate", districtId: "tinsukia", reportedAt: "3h 02m ago", source: "NER-LOGIX Reports" },
];

export const INCIDENT_POINTS: Array<Incident & { lat: number; lng: number }> = [
  { ...INCIDENTS[0], lat: 25.36, lng: 92.37 },
  { ...INCIDENTS[1], lat: 24.86, lng: 92.9 },
  { ...INCIDENTS[2], lat: 27.49, lng: 95.36 },
];

export interface SimulatedRoute {
  id: string;
  label: string;
  risk: RiskLevel;
  path: Array<[number, number]>;
  source: DataSource;
}

export const ROUTES: SimulatedRoute[] = [
  {
    id: "R-01",
    label: "Dibrugarh — Guwahati corridor",
    risk: "moderate",
    path: [
      [27.47, 94.91],
      [26.75, 94.21],
      [26.35, 92.68],
      [26.14, 91.73],
    ],
    source: "NER-LOGIX Simulation",
  },
  {
    id: "R-02",
    label: "Shillong — Guwahati corridor",
    risk: "safe",
    path: [
      [25.57, 91.88],
      [25.9, 91.87],
      [26.14, 91.73],
    ],
    source: "NER-LOGIX Simulation",
  },
  {
    id: "R-03",
    label: "Silchar — Shillong corridor",
    risk: "high",
    path: [
      [24.82, 92.79],
      [25.36, 92.37],
      [25.57, 91.88],
    ],
    source: "NER-LOGIX Simulation",
  },
  {
    id: "R-04",
    label: "Tinsukia — Jorhat corridor",
    risk: "blocked",
    path: [
      [27.49, 95.36],
      [27.47, 94.91],
      [26.75, 94.21],
    ],
    source: "NER-LOGIX Simulation",
  },
];

export const MISSIONS: TransportMission[] = [
  {
    code: "MISSION 001",
    type: "Logistics",
    descriptorLabel: "Cargo",
    descriptor: "Essential Supplies",
    origin: "Dibrugarh",
    destination: "Guwahati",
    status: "En Route",
    progress: 58,
    eta: "04h 20m",
    riskLabel: "Moderate",
    risk: "moderate",
    simulated: true,
  },
  {
    code: "MISSION 002",
    type: "Medical",
    descriptorLabel: "Service",
    descriptor: "Emergency Medical Transfer",
    origin: "Shillong",
    destination: "Guwahati",
    status: "En Route",
    progress: 41,
    eta: "01h 05m",
    riskLabel: "Emergency",
    risk: "high",
    priority: "Emergency",
    simulated: true,
  },
];

export type AlertCategory = "government-weather" | "nerlogix-incident" | "simulation";

export interface AlertItem {
  id: string;
  category: AlertCategory;
  title: string;
  detail: string;
  severity: RiskLevel;
  location: string;
  time: string;
}

export const ALERT_GROUP_META: Record<
  AlertCategory,
  { title: string; source: string; tone: string }
> = {
  "government-weather": {
    title: "Government Weather Alerts",
    source: "Source: India Meteorological Department",
    tone: "border-primary/40 bg-primary/10 text-primary",
  },
  "nerlogix-incident": {
    title: "NER-LOGIX Incident Alerts",
    source: "Source: NER-LOGIX",
    tone: "border-high/40 bg-high/10 text-high",
  },
  simulation: {
    title: "Simulation Alerts",
    source: "Source: NER-LOGIX Demo",
    tone: "border-border-strong bg-muted text-muted-foreground",
  },
};

/** No government weather alerts are listed: none can be retrieved without the IMD proxy. */
export const ALERTS: AlertItem[] = [
  {
    id: "ALR-4405",
    category: "nerlogix-incident",
    title: "Landslide debris reported",
    detail: "Field report: debris blocking a single-lane stretch (INC-2291).",
    severity: "blocked",
    location: "East Jaintia Hills",
    time: "51 min ago",
  },
  {
    id: "ALR-4412",
    category: "nerlogix-incident",
    title: "Road erosion reported",
    detail: "Field report: shoulder erosion on the Tinsukia approach (INC-2284).",
    severity: "moderate",
    location: "Tinsukia",
    time: "3h 02m ago",
  },
  {
    id: "ALR-4398",
    category: "simulation",
    title: "Medical route priority active",
    detail: "Demo scenario: corridor clearance granted for MISSION 002 transfer.",
    severity: "safe",
    location: "Shillong — Guwahati",
    time: "1h 12m ago",
  },
];
